language: php
php:
- '5.4'
- '5.6'
services:
  - docker
script:
- phpunit --version
# test image
- docker build -t banmanagementwebplus .
- docker run --name banmanagementwebplus -d banmanagementwebplus:latest
- docker ps -a
deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: import.sql
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    target_branch: master
    on:
      branch: Dev